# Generated by Django 4.0.3 on 2022-03-31 22:16

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Catégorie'},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'Client'},
        ),
        migrations.AlterModelOptions(
            name='features',
            options={'verbose_name': 'Fonctionnalité'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Projet'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Service'},
        ),
        migrations.AddField(
            model_name='services',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de Création'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='features',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='features',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='features',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='features',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='features',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devis.services', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='features',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modidification'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devis.clients', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coût'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='delay',
            field=models.DateTimeField(verbose_name='Délai de livraison'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Libellé'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='services',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='services',
            name='delay',
            field=models.CharField(max_length=255, verbose_name='Délai de livraison'),
        ),
        migrations.AlterField(
            model_name='services',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='services',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière modification'),
        ),
    ]
