# Generated by Django 4.0.3 on 2022-04-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0006_remove_projects_name_alter_projects_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='services',
            field=models.JSONField(null=True, verbose_name='Services'),
        ),
    ]
