# Generated by Django 4.0.3 on 2022-04-20 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0007_projects_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='services',
        ),
    ]
