# Generated by Django 4.0.3 on 2022-04-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0008_remove_projects_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_state',
            field=models.CharField(default='Devis', max_length=255),
        ),
        migrations.AddField(
            model_name='projects',
            name='request_state',
            field=models.IntegerField(choices=[(0, 'En attente'), (1, 'Validé'), (2, 'Supprimé')], default=0),
            preserve_default=False,
        ),
    ]
