# Generated by Django 4.0.3 on 2022-04-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0009_projects_project_state_projects_request_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='client',
        ),
        migrations.AddField(
            model_name='projects',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='projects',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='projects',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='projects',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='projects',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
